name: CoreTags
version: '${version}'
main: io.rhythmknights.coretags.CoreTags
api-version: '1.13'
authors: [RhythmKnights]
description: '${description}'
depend: [CoreFramework]
commands:
  coretags:
    description: CoreTags main command
    usage: /<command> [reload]
    permission: coretags.admin